# ClusterIP service to expose HTTPBin internally
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
  namespace: httpbin
spec:
  type: ClusterIP
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http  # Port mapping for the service